ln,bot: convert ln to TS (#646)
* ln,bot: convert ln to TS

Convert ln module to TypeScript.

* package.json: install type packages

Add type packages needed for Typescript code to package.json.

* use eslint on TS files

Setup eslint so that it checks .ts files instead of .js.

* fix eslint import ordering errors

Fix "Import in body of module; reorder to top  import/first"
eslint errors.

* bot: change signature of notAuthorized function

From Promise<void> to Promise<undefined>, to get rid of the
following error:
```
tests/bot/validation.spec.ts(376,19): error TS2339: Property 'tg_id' does not exist on type 'void | (UserDocument & { _id: ObjectId; })'.
  Property 'tg_id' does not exist on type 'void'.
```

* fix more eslint errors

* eslint: silenced remaining errors

Silenced remaining eslint errors as what they refer to is
intended behavior.