bot/modules/nostr: convert to TS (#627)
* bot/modules/nostr: convert to TS

Convert bot/modules/nostr to TypeScript.
Specified "lib" property in tsconfig.json because otherwise
TypeScript compiler complains about usage of `Promise.any`
in bot/modules/nostr/index.ts:
```
Property 'any' does not exist on type 'PromiseConstructor'. Do you need to change your target library? Try changing the lib compiler option to 'es2021' or later.
```

* bot/modules/nostr: decode nostr sk from env. var

Decode nostr secret key from environment variable using hex
encoding. Also replace requires with imports.

* bot/modules/nostr: move CommunityEvents import to top

* bot/modules/nostr: fix imports

Using `Nostr` from `nostr-tools` as before resulted in error:
```
Cannot read properties of undefined (reading 'nip19') TypeError: Cannot read properties of undefined (reading 'nip19')
```